# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d50532954e039085c16e33759139804c62f3f7e1559489454fa3dedfc5f0748d2b226d41e6ea97687a46c253427b6875784a0736622e3ffdc459eb404c9295c2

test:
  secret_key_base: 06869f7d14ab3fea158a15e97939c2abde209a023e4ce6f5e16de64d0ef918784103eb1d66e81fa0eaa30179a7858a375d6a63537fcbd29b17b57c274da2c6c3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
