Contact.create(first_name: "Luke", last_name: "Skywalker", email: "lukeskywalker@gmail.com", phone_number: "224-123-4567")
Contact.create(first_name: "Bilbo", last_name: "Baggins", email: "bilbobaggins@gmail.com", phone_number: "312-123-4567")
Contact.create(first_name: "Darth", last_name: "Vader", email: "darthvader@gmail.com", phone_number: "847-123-4567")
Contact.create(first_name: "Harry", last_name: "Potter", email: "harrypotter@gmail.com", phone_number: "815-123-4567")
Contact.create(first_name: "Hermione", last_name: "Grainger", email: "hermionegrainger@gmail.com", phone_number: "773-123-4567")